#!/bin/bash
# ANSI font variant test script

reset="\e[0m"
bold="\e[1m"
italic="\e[3m"
underline="\e[4m"
blink="\e[5m"
reverse="\e[7m"
bold_italic="\e[1;3m"
bold_underline="\e[1;4m"
italic_underline="\e[3;4m"
bold_italic_underline="\e[1;3;4m"

echo -e "${reset}"
echo -e "=== Font Variant Test ==="
echo -e ""
echo -e "Regular:              ${reset}The quick brown fox jumps over the lazy dog${reset}"
echo -e "Bold:                 ${bold}The quick brown fox jumps over the lazy dog${reset}"
echo -e "Italic:               ${italic}The quick brown fox jumps over the lazy dog${reset}"
echo -e "Bold Italic:          ${bold_italic}The quick brown fox jumps over the lazy dog${reset}"
echo -e ""
echo -e "Underline:            ${underline}The quick brown fox jumps over the lazy dog${reset}"
echo -e "Bold + Underline:     ${bold_underline}The quick brown fox jumps over the lazy dog${reset}"
echo -e "Italic + Underline:   ${italic_underline}The quick brown fox jumps over the lazy dog${reset}"
echo -e "Bold+Italic+Underline:${bold_italic_underline}The quick brown fox jumps over the lazy dog${reset}"
echo -e ""
echo -e "=== Colors ==="
echo -e ""
for i in 30 31 32 33 34 35 36 37; do
    echo -e "  \e[${i}mRegular  \e[1m Bold  \e[0m\e[3;${i}mItalic  \e[1;3;${i}mBold Italic${reset}"
done
echo -e ""
echo -e "=== Bright Colors ==="
echo -e ""
for i in 90 91 92 93 94 95 96 97; do
    echo -e "  \e[${i}mRegular  \e[1m Bold  \e[0m\e[3;${i}mItalic  \e[1;3;${i}mBold Italic${reset}"
done
echo -e ""
echo -e "=== Reverse + Bold ==="
echo -e ""
echo -e "  ${reverse}Reverse${reset}  ${bold}${reverse}Bold Reverse${reset}  ${italic}${reverse}Italic Reverse${reset}"
echo -e ""
echo -e "=== Emoji ==="
echo -e ""
echo -e "  Regular: 👍 🎉 ❤️  🔥 ✨ 🐧 ♔ ♕ ♖"
echo -e "  Bold:    ${bold}👍 🎉 ❤️  🔥 ✨ 🐧 ♔ ♕ ♖${reset}"
echo -e ""
echo -e "=== Mixed ==="
echo -e ""
echo -e "  \e[32mGreen${reset} \e[1;32mBold Green${reset} \e[3;32mItalic Green${reset} \e[1;3;32mBold Italic Green${reset} \e[4;32mUnderline Green${reset}"
echo -e "  \e[31mRed${reset} \e[1;31mBold Red${reset} \e[3;31mItalic Red${reset} \e[1;3;31mBold Italic Red${reset} \e[4;31mUnderline Red${reset}"
echo -e ""
echo -e "${reset}Done."
