#!/usr/bin/env python3
"""
gen_levels_header.py — Converts levels.json into a C header file.

Usage:
    python3 gen_levels_header.py [levels.json] [wopr_willy_levels.h]

Defaults to levels.json and wopr_willy_levels.h in the current directory.
"""

import sys, os

LEVELS_FILE = sys.argv[1] if len(sys.argv) > 1 else "levels.json"
HEADER_FILE = sys.argv[2] if len(sys.argv) > 2 else "wopr_willy_levels.h"

if not os.path.exists(LEVELS_FILE):
    sys.exit(f"ERROR: {LEVELS_FILE} not found")

data = open(LEVELS_FILE, "rb").read()

lines = []
lines.append("// Auto-generated by gen_levels_header.py — do not edit by hand.")
lines.append("// Regenerate with:  python3 gen_levels_header.py levels.json wopr_willy_levels.h")
lines.append("#pragma once")
lines.append("")
lines.append("static const char s_levels_json[] =")

# Emit as a C string literal, breaking into lines of 120 chars each
chunk_size = 120
json_str = data.decode("utf-8")

chunks = [json_str[i:i+chunk_size] for i in range(0, len(json_str), chunk_size)]
for i, chunk in enumerate(chunks):
    escaped = chunk.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    suffix = "" if i < len(chunks) - 1 else ";"
    lines.append(f'    "{escaped}"{suffix}')

lines.append("")
lines.append(f"static const size_t s_levels_json_len = {len(data)};")
lines.append("")

open(HEADER_FILE, "w").write("\n".join(lines))
print(f"Generated {HEADER_FILE} ({len(data):,} bytes of JSON, {len(chunks)} string chunks)")
