#!/usr/bin/env python3
"""
gen_willy_assets.py — Compresses levels.json and willy.chr with zlib and
writes them as C byte arrays into wopr_willy_assets.h.

Usage:
    python3 gen_willy_assets.py [levels.json] [willy.chr] [wopr_willy_assets.h]

Defaults to files in the current directory.
"""

import zlib, sys, os

LEVELS_FILE = sys.argv[1] if len(sys.argv) > 1 else "levels.json"
CHR_FILE    = sys.argv[2] if len(sys.argv) > 2 else "willy.chr"
HEADER_FILE = sys.argv[3] if len(sys.argv) > 3 else "wopr_willy_assets.h"

for path in (LEVELS_FILE, CHR_FILE):
    if not os.path.exists(path):
        sys.exit(f"ERROR: {path} not found")

def make_blob(path):
    raw  = open(path, "rb").read()
    comp = zlib.compress(raw, 9)
    rows = []
    row  = []
    for b in comp:
        row.append(f"0x{b:02x}")
        if len(row) == 16:
            rows.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        rows.append("    " + ", ".join(row))
    return raw, comp, rows

levels_raw, levels_comp, levels_rows = make_blob(LEVELS_FILE)
chr_raw,    chr_comp,    chr_rows    = make_blob(CHR_FILE)

lines = [
    "// Auto-generated by gen_willy_assets.py — do not edit by hand.",
    f"// Regenerate: python3 gen_willy_assets.py {LEVELS_FILE} {CHR_FILE} {HEADER_FILE}",
    "#pragma once",
    "#include <stddef.h>",
    "",
    "// ---- levels.json --------------------------------------------------------",
    f"// Raw: {len(levels_raw):,} bytes   Compressed: {len(levels_comp):,} bytes",
    "static const unsigned char willy_levels_z[] = {",
] + levels_rows + [
    "};",
    f"static const size_t willy_levels_z_len   = {len(levels_comp)};",
    f"static const size_t willy_levels_raw_len = {len(levels_raw)};",
    "",
    "// ---- willy.chr ----------------------------------------------------------",
    f"// Raw: {len(chr_raw):,} bytes   Compressed: {len(chr_comp):,} bytes",
    "static const unsigned char willy_chr_z[] = {",
] + chr_rows + [
    "};",
    f"static const size_t willy_chr_z_len   = {len(chr_comp)};",
    f"static const size_t willy_chr_raw_len = {len(chr_raw)};",
    "",
]

open(HEADER_FILE, "w").write("\n".join(lines))
print(f"Generated {HEADER_FILE}")
print(f"  levels.json : {len(levels_raw):>7,} -> {len(levels_comp):>6,} bytes")
print(f"  willy.chr   : {len(chr_raw):>7,} -> {len(chr_comp):>6,} bytes")
print(f"  Total binary overhead: {len(levels_comp) + len(chr_comp):,} bytes")
