#pragma once

// ============================================================================
// WOPR SALUTE REPORT DATABASE
//
// SALUTE format:
//   S - SIZE       Strength of enemy element
//   A - ACTIVITY   What the enemy is doing
//   L - LOCATION   Where (grid, coordinates, landmark)
//   U - UNIFORM    Dress, markings, identification
//   T - TIME       DTG of observation
//   E - EQUIPMENT  Weapons, vehicles, support gear
//
// Each SaluteReport is a self-contained observation from a single source.
// Pull randomly from this pool; display 3-5 per SITREP.
// ============================================================================

struct SaluteReport {
    const char *report_id;    // e.g. "SALUTE-047"
    const char *source;       // intel origin line
    const char *size;
    const char *activity;
    const char *activity2;    // second line of activity (may be nullptr)
    const char *location;
    const char *location2;    // second line (may be nullptr)
    const char *uniform;
    const char *uniform2;     // second line (may be nullptr)
    const char *time_dtg;
    const char *equipment;
    const char *equipment2;   // second line (may be nullptr)
};

static const SaluteReport SALUTE_POOL[] = {

    // ── GROUND / ARMOR ────────────────────────────────────────────────────

    {
        "SALUTE-001",
        "HUMINT ASSET FOXGLOVE",
        "BATTALION MINUS (~350 PERSONNEL)",
        "FORWARD ASSEMBLY, BRIDGING EQUIPMENT",
        "BEING STAGED AT RIVER CROSSING SITE",
        "GRID 447-882, ELBE RIVER WEST BANK",
        "APPROX 14KM NE OF MAGDEBURG",
        "SOVIET MOTOR RIFLE, SUMMER DRESS",
        "CHEMICAL PROTECTION SUITS OBSERVED",
        "030147Z JUN 83",
        "12x T-72 MBT, 8x BMP-1, 4x PMP",
        "PONTOON BRIDGE SECTIONS, 2x SA-9 GASKIN"
    },
    {
        "SALUTE-002",
        "NRO KEYHOLE-11 PASS 7734",
        "REGIMENT (~1,800 PERSONNEL EST.)",
        "DISPERSAL FROM GARRISON, MOVING EAST",
        "TO WEST.  TACTICAL COLUMN FORMATION.",
        "AUTOBAHN E40, 22KM WEST OF LEIPZIG",
        "COORDINATES: 51.21N  11.87E",
        "INDETERMINATE FROM IMAGERY ALTITUDE",
        "MARKINGS CONSISTENT W/ 3RD SHOCK ARMY",
        "030312Z JUN 83",
        "40+ AFVs, 2S3 AKATSIYA 152MM SP HOWITZERS",
        "1x ZSU-23-4 SHILKA AIR DEFENSE"
    },
    {
        "SALUTE-003",
        "HUMINT ASSET BROADLEAF / CONFIRMED BY IMAGERY",
        "COMPANY (~120 PERSONNEL)",
        "OCCUPYING DEFENSIVE FIGHTING POSITIONS",
        "ALONG RIDGE LINE, FIELDS OF FIRE TO WEST",
        "GRID 512-341, THURINGIAN FOREST",
        "APPROX 6KM SOUTH OF EISENACH",
        "EAST GERMAN NVA MOTORIZED INFANTRY",
        "WINTER CAMOUFLAGE OVER STANDARD DRESS",
        "022318Z JUN 83",
        "4x BMP-2, 2x 120MM MORTAR, ATGM POSITIONS",
        "AT-4 SPIGOT LAUNCHERS EMPLACED"
    },
    {
        "SALUTE-004",
        "GUARDRAIL SIGINT AIRCRAFT TRACK 14",
        "BATTALION (+) (~600 PERSONNEL)",
        "RAPID ROAD MARCH NORTHBOUND",
        "SPEED SUGGESTS MOVEMENT TO CONTACT",
        "HIGHWAY B96, APPROX 30KM S OF ROSTOCK",
        "COORDINATES: 54.08N  12.14E",
        "UNKNOWN -- NO VISUAL CONTACT",
        "VEHICLE ENGINE SIGNATURES CONSISTENT",
        "030504Z JUN 83",
        "TRACKED VEHICLE COUNT: 60+ BY ACOUSTIC",
        "LIKELY T-64B OR T-80 BY ENGINE SIGNATURE"
    },
    {
        "SALUTE-005",
        "ODA-713 GROUND OBSERVATION POST",
        "PLATOON (~40 PERSONNEL)",
        "ESTABLISHING OBSERVATION POST ON HIGH",
        "GROUND OVERLOOKING NATO SUPPLY ROUTE",
        "HILL 412, GRID 229-774",
        "HARZ MOUNTAINS, APPROX 8KM NW OF NORDHAUSEN",
        "SOVIET SPETSNAZ, NO RANK INSIGNIA",
        "CIVILIAN VEHICLE COVERS, GERMAN PLATES",
        "022047Z JUN 83",
        "MANPADS (SA-14 GREMLIN), RPG-7",
        "ENCRYPTED RADIO, OPTICAL SURVEILLANCE GEAR"
    },
    {
        "SALUTE-006",
        "CZECH BORDER WATCH POST ZETA-4",
        "DIVISION ELEMENTS (~4,000 PERSONNEL)",
        "STAGED IN ASSEMBLY AREAS, ENGINES RUNNING",
        "MULTIPLE UNIT PATCHES OBSERVED -- MIXED FORMATION",
        "SUDETENLAND STAGING AREA COMPLEX BRAVO",
        "APPROX 25KM EAST OF CHEB, CZECHOSLOVAKIA",
        "SOVIET AND CZECH COMBINED ARMS",
        "FULL NBC GEAR, MASKS AT READY POSITION",
        "030001Z JUN 83",
        "T-72, BMP-1, BTR-80, MULTIPLE BM-21 GRAD MRLS",
        "DIVISIONAL ARTILLERY GROUP: 2S1, 2S3 MIXED"
    },
    {
        "SALUTE-007",
        "HUMINT SOURCE CARDINAL (RELIABILITY: B2)",
        "SPECIAL PURPOSE COMPANY (~90 PERSONNEL)",
        "REHEARSING AIRFIELD SEIZURE PROCEDURES",
        "ON MOCK-UP FACILITY, NIGHT OPERATIONS",
        "TRAINING AREA ALPHA-7, EAST OF COTTBUS",
        "COORDINATES: 51.77N  14.51E",
        "GRU SPETSNAZ BRIGADE, STERILE UNIFORMS",
        "NO UNIT MARKINGS, GERMAN-LANGUAGE PATCHES",
        "012200Z JUN 83",
        "PERSONAL WEAPONS ONLY DURING OBSERVATION",
        "FACILITY SUGGESTS HELIBORNE ASSAULT TRAINING"
    },
    {
        "SALUTE-008",
        "AERIAL RECONNAISSANCE RF-4C MISSION 441",
        "BRIGADE (~2,200 PERSONNEL)",
        "CONCEALED IN WOODED AREA, VEHICLE",
        "CAMOUFLAGE NETS DEPLOYED -- HIDING FROM AIR",
        "FOREST COMPLEX GRID 661-203",
        "15KM NW OF FRANKFURT AN DER ODER",
        "SOVIET 1ST GUARDS TANK ARMY MARKINGS",
        "FULL COMBAT LOAD, REACTIVE ARMOR OBSERVED",
        "030219Z JUN 83",
        "T-80U MBT (NEW VARIANT), BMP-2, BRDM-2",
        "SA-13 GOPHER AIR DEFENSE, PRP-3 ARTY RECON"
    },
    {
        "SALUTE-009",
        "GROUND SENSOR ARRAY FENCE-LINE TANGO",
        "PLATOON TO COMPANY (~60 PERSONNEL)",
        "INFILTRATION THROUGH GAP IN BORDER FENCE",
        "MOVING IN SMALL ELEMENTS, 10-MIN INTERVALS",
        "IZ-WEST CROSSING POINT NOVEMBER",
        "GRID 084-519, BAVARIAN FOREST SECTOR",
        "CAMOUFLAGE CONSISTENT WITH CZECH 1ST ARMY",
        "FACE PAINT, NO HEADGEAR OBSERVED",
        "022347Z JUN 83",
        "LIGHT INFANTRY LOADOUT, ATGM TUBES",
        "NO HEAVY EQUIPMENT -- LIKELY RECCE IN FORCE"
    },
    {
        "SALUTE-010",
        "IMAGERY ANALYST ASSESSMENT -- DIA PRODUCTION",
        "ARMY-LEVEL LOGISTICS ELEMENT (~800 VEHICLES)",
        "FUEL AND AMMUNITION FORWARD POSITIONING",
        "INDICATES OFFENSIVE OPERATIONS WITHIN 72HRS",
        "LOGISTICS BASE CHARLIE, GRID 780-110",
        "EAST OF MAGDEBURG, COORD: 52.19N  12.03E",
        "SOVIET REAR SERVICES, MIXED DRESS",
        "CIVILIAN TRUCKS PRESSED INTO MILITARY USE",
        "030000Z JUN 83",
        "FUEL TANKERS (ZIL-131), AMMUNITION CARRIERS",
        "ESTIMATED 500,000L FUEL, 2,000 TONS AMMO"
    },

    // ── NAVAL ─────────────────────────────────────────────────────────────

    {
        "SALUTE-011",
        "P-3C ORION MARITIME PATROL -- CREW 7",
        "1x SUBMARINE (NOVEMBER-CLASS SSN)",
        "SNORKELING, CHARGING BATTERIES",
        "HEADING 270, SPEED 8 KNOTS",
        "NORTH ATLANTIC, 63.4N  018.2W",
        "APPROX 200NM SOUTHWEST OF ICELAND",
        "SOVIET NORTHERN FLEET",
        "IDENTIFICATION CONFIRMED BY ACOUSTIC",
        "030821Z JUN 83",
        "TORPEDO TUBES -- STANDARD LOADOUT ASSUMED",
        "NO WEAPONS FREE INDICATORS OBSERVED"
    },
    {
        "SALUTE-012",
        "USS PERMIT (SSN-594) CONTACT REPORT",
        "SURFACE ACTION GROUP (3 VESSELS)",
        "UNDERWAY REPLENISHMENT IN PROGRESS",
        "SUGGESTS EXTENDED PATROL DURATION INTENDED",
        "BARENTS SEA, 72.1N  033.8E",
        "APPROX 140NM NORTH OF MURMANSK",
        "SOVIET NORTHERN FLEET -- KIROV-CLASS LEAD",
        "KIROV CGN + 2x UDALOY-CLASS DDG",
        "021944Z JUN 83",
        "KIROV: SS-N-19 SHIPWRECK ASMs, SA-N-6",
        "UDALOY: SS-N-14 SILEX ASW MISSILES"
    },
    {
        "SALUTE-013",
        "SOSUS ARRAY NOVEMBER-7 DETECTION",
        "2x SUBMARINES (DELTA-III CLASS SSBN)",
        "PATROL TRANSIT, MOVING TO LAUNCH BOX",
        "BOTH VESSELS MAINTAINING ACOUSTIC QUIET",
        "NORWEGIAN SEA, 68N  002E (ESTIMATED)",
        "TRACKING UNCERTAINTY: +/- 40NM",
        "SOVIET STRATEGIC ROCKET FORCES (NAVAL)",
        "ACOUSTIC IDENTIFICATION ONLY",
        "030614Z JUN 83",
        "16x SS-N-18 STINGRAY SLBMs EACH",
        "ESTIMATED YIELD: 200KT MRV -- 7 WARHEADS/MISSILE"
    },
    {
        "SALUTE-014",
        "DANISH STRAIT MONITORING STATION",
        "SURFACE TASK GROUP (6 VESSELS)",
        "TRANSIT THROUGH DANISH STRAITS",
        "HEADING SOUTHWEST INTO NORTH SEA",
        "GREAT BELT, 55.3N  010.9E",
        "TRANSITING FROM BALTIC TO NORTH SEA",
        "SOVIET BALTIC FLEET",
        "FULL WARTIME DAMAGE CONTROL POSTURE",
        "030409Z JUN 83",
        "SLAVA-CLASS CG, 4x SOVREMENNYY DDG, 1x REPLENISHMENT",
        "AA RADARS IN ACTIVE EMISSION -- HOSTILE POSTURE"
    },
    {
        "SALUTE-015",
        "NAVAL ATTACHE REPORT -- OSLO STATION",
        "AMPHIBIOUS READY GROUP (8 VESSELS)",
        "ASSEMBLED IN PECHENGA FJORD",
        "MARINES EMBARKED, LANDING CRAFT LOWERED",
        "PECHENGA FJORD, 69.5N  031.2E",
        "APPROX 10NM FROM NORWEGIAN BORDER",
        "SOVIET NAVAL INFANTRY -- BLACK BERET",
        "FULL COMBAT GEAR, ARCTIC CAMOUFLAGE",
        "030300Z JUN 83",
        "IVAN ROGOV-CLASS LPD, LST, HOVERCRAFT",
        "BMP-1 MARINIZED, PT-76 AMPHIBIOUS TANKS"
    },

    // ── AIR ───────────────────────────────────────────────────────────────

    {
        "SALUTE-016",
        "HAWK BATTERY RADAR TRACK -- SECTOR ALPHA",
        "FLIGHT OF 4 AIRCRAFT",
        "LOW-LEVEL PENETRATION PROFILE",
        "TERRAIN-FOLLOWING, NOE ALTITUDE",
        "GRID 334-445, FULDA GAP CORRIDOR",
        "BEARING 280, HEADING WEST",
        "SOVIET FRONTAL AVIATION -- SU-24 FENCER",
        "CAMOUFLAGE GREY/GREEN LOW-VIS SCHEME",
        "030347Z JUN 83",
        "ESTIMATED EXTERNAL STORES: AS-7 KERRY AGMs",
        "ECM PODS OBSERVED ON WING STATIONS"
    },
    {
        "SALUTE-017",
        "AWACS E-3 SENTRY TRACK FILE 7721",
        "REGIMENT (24 AIRCRAFT IN 6 FLIGHTS)",
        "OFFENSIVE COUNTER-AIR SWEEP",
        "COORDINATED WITH GROUND RADAR EMISSIONS",
        "EAST GERMAN AIRSPACE, COORD: 52.8N  13.9E",
        "INBOUND WEST -- 180NM FROM IGB",
        "SOVIET 16TH AIR ARMY, FRONTAL AVIATION",
        "GREY AIR SUPERIORITY SCHEME",
        "030258Z JUN 83",
        "MIG-29 FULCRUM -- AA-10 ALAMO + AA-11 ARCHER",
        "SUPPORTED BY 2x IL-76 MAINSTAY AEW AIRCRAFT"
    },
    {
        "SALUTE-018",
        "RHEINMAIN AFB RADAR / CONFIRMED BY FIGHTER CAP",
        "FLIGHT OF 2 AIRCRAFT",
        "ELECTRONIC INTELLIGENCE COLLECTION",
        "ORBITING PATTERN ALONG IGB -- NOT CROSSING",
        "EAST GERMAN AIRSPACE, ALONG IGB",
        "COORDINATES: 50.4N  012.6E",
        "SOVIET RECONNAISSANCE AVIATION",
        "STANDARD SOVIET GREY, NO MARKINGS",
        "021719Z JUN 83",
        "TU-16 BADGER-D ELINT VARIANT",
        "ACTIVE EMISSIONS: SIDE-LOOKING RADAR, ELINT PODS"
    },
    {
        "SALUTE-019",
        "CZECH AIR DEFENSE DEFECTOR DEBRIEF",
        "SQUADRON (12 AIRCRAFT)",
        "DISPERSAL TO ALTERNATE FIELDS",
        "CONSISTENT WITH PRE-HOSTILITY POSTURE",
        "ZATEC AND PRIBRAM AIRFIELDS, CZECHOSLOVAKIA",
        "APPROXIMATELY 60KM SOUTHWEST OF PRAGUE",
        "CZECH AIR FORCE / SOVIET LOAN CREWS",
        "NUCLEAR STORAGE FACILITY ACTIVATED AT BOTH",
        "022100Z JUN 83",
        "SU-22 FITTER WITH NUCLEAR-CAPABLE PYLONS",
        "GROUND CREWS OBSERVED WITH DOSIMETERS"
    },
    {
        "SALUTE-020",
        "LUFTWAFFE RADAR STATION HOHER BOGEN",
        "FLIGHT OF 6 AIRCRAFT",
        "AIRBORNE ASSAULT INSERTION",
        "LOW-LEVEL, NAPE-OF-EARTH, NIGHT APPROACH",
        "GRID 881-207, BAVARIAN FOREST",
        "APPROX 40KM EAST OF REGENSBURG",
        "SOVIET FRONTAL AVIATION TRANSPORT",
        "AIRCRAFT LIGHTS EXTINGUISHED",
        "030148Z JUN 83",
        "AN-12 CUB TRANSPORT -- 6 SORTIES",
        "ESTIMATED 350 AIRBORNE TROOPS INSERTED"
    },

    // ── MISSILE / WMD ─────────────────────────────────────────────────────

    {
        "SALUTE-021",
        "DSP SATELLITE DETECTION / CONFIRMED",
        "BATTALION MISSILE UNIT (4 TELs)",
        "LAUNCH SITE PREPARATION COMPLETE",
        "ERECTION AND FUELING SEQUENCE OBSERVED",
        "GRID 774-003, POLAND",
        "APPROX 80KM EAST OF WARSAW",
        "SOVIET 69TH MISSILE BRIGADE",
        "FULL NUCLEAR-CAPABLE UNIT MARKINGS",
        "030512Z JUN 83",
        "SS-20 SABER (RSD-10) IRBM",
        "3x 150KT MIRVs -- RANGE: 5,000KM"
    },
    {
        "SALUTE-022",
        "HUMINT ASSET REDWOOD -- RELIABILITY A1",
        "BATTERY (4 LAUNCHERS)",
        "TACTICAL NUCLEAR RELOAD OPERATION",
        "OBSERVED AT FORWARD STORAGE SITE",
        "GRID 512-884, EAST GERMAN BORDER ZONE",
        "COORDINATES: 52.88N  014.04E",
        "SOVIET GROUND FORCES, NUCLEAR ARTILLERY",
        "SPECIAL WEAPONS HANDLING DRESS",
        "022349Z JUN 83",
        "2S7 PION 203MM NUCLEAR-CAPABLE SP GUN",
        "WARHEAD CANISTERS -- TYPE 3BV3 CONFIRMED"
    },
    {
        "SALUTE-023",
        "DIA / NSA JOINT ASSESSMENT",
        "REGIMENT (12 LAUNCHERS)",
        "DISPERSAL FROM GARRISON TO FIELD SITES",
        "EMISSIONS CONSISTENT WITH TARGETING RADAR",
        "CENTRAL UKRAINE, APPROX 49.5N  028.7E",
        "MULTIPLE DISPERSAL SITES, 10KM SEPARATION",
        "SOVIET STRATEGIC ROCKET FORCES",
        "STANDARD OPERATIONAL DRESS, NO NBC GEAR",
        "030215Z JUN 83",
        "SS-4 SANDAL MRBM (OLDER BUT OPERATIONAL)",
        "ESTIMATED 1MT SINGLE WARHEAD -- TARGETS: W. EUROPE"
    },
    {
        "SALUTE-024",
        "CHEMICAL DETECTION TEAM BRAVO-7",
        "COMPANY (~80 PERSONNEL)",
        "CHEMICAL AGENT DISPERSAL REHEARSAL",
        "USING INERT SIMULANT -- ACTUAL AGENT STORED",
        "TRAINING AREA 14, EAST GERMANY",
        "GRID 304-711, 30KM NW OF ERFURT",
        "SOVIET CHEMICAL TROOPS (KHIMICHESKIYE VOYSKA)",
        "FULL MISSION-ORIENTED PROTECTIVE POSTURE",
        "022004Z JUN 83",
        "TMS-65 DECONTAMINATION VEHICLES",
        "SUSPECTED NERVE AGENT STORAGE: VX / NOVICHOK"
    },

    // ── SIGINT / DECEPTION / OTHER ────────────────────────────────────────

    {
        "SALUTE-025",
        "SIGINT NSA STATION AUGSBURG",
        "COMPANY-SIZED ELEMENT (~80 PERSONNEL)",
        "RADIO TRAFFIC SURGE, ENCRYPTED BURST TX",
        "CONSISTENT WITH PRE-MISSION COORDINATION",
        "BEARING TRIANGULATION: 52.4N  013.1E",
        "WEST BERLIN CORRIDOR VICINITY",
        "UNKNOWN -- NO VISUAL CONFIRMATION",
        nullptr,
        "030023Z JUN 83",
        "COMMS EQUIPMENT ONLY -- R-350M INFERRED",
        "NO HEAVY EQUIPMENT SIGNATURES DETECTED"
    },
    {
        "SALUTE-026",
        "PSYCHOLOGICAL OPERATIONS MONITORING UNIT",
        "UNKNOWN (BROADCAST ORIGIN TRIANGULATED)",
        "RADIO BROADCAST ON NATO FREQ -- DECEPTION",
        "IMPERSONATING USAREUR COMMAND NET",
        "TRANSMITTER LOCATED: 52.1N  014.5E",
        "EAST GERMANY, MOBILE PLATFORM",
        "UNKNOWN -- ELECTRONIC ONLY",
        nullptr,
        "030330Z JUN 83",
        "HIGH-POWER HF TRANSMITTER",
        "CONTENT: FALSE WITHDRAWAL ORDERS IN ENGLISH"
    },
    {
        "SALUTE-027",
        "HUMINT ASSET BIRCHWOOD",
        "ENGINEER BATTALION (~500 PERSONNEL)",
        "OBSTACLE BREACHING REHEARSAL",
        "WIRE, MINEFIELD LANES, AT DITCHES",
        "TRAINING COMPLEX EAST, GRID 119-334",
        "APPROX 45KM NE OF BERLIN",
        "SOVIET COMBAT ENGINEERS, SUMMER DRESS",
        "UNIT PATCH: 3RD COMBINED ARMS ARMY",
        "021500Z JUN 83",
        "IMR COMBAT ENGINEER VEHICLES, MTU-72 BRIDGELAYERS",
        "UR-77 MINE CLEARING LINE CHARGE (MICLIC)"
    },
    {
        "SALUTE-028",
        "BORDER GUARD OBSERVATION POST LIMA-9",
        "PLATOON (~35 PERSONNEL)",
        "EMPLACING FORWARD OBSERVATION EQUIPMENT",
        "LASER RANGE FINDERS, THERMAL IMAGING",
        "HILL 387, GRID 441-628",
        "IGB, SECTOR FOXTROT -- 2KM EAST OF BORDER",
        "SOVIET GROUND FORCES RECON PLATOON",
        "CAMOUFLAGE SMOCKS, NO RANK VISIBLE",
        "030048Z JUN 83",
        "BRM-1K RECON VEHICLE, PORTABLE RADAR",
        "SMALL ARMS + ATGM -- RECCE CONFIGURATION"
    },
    {
        "SALUTE-029",
        "SATELLITE IMAGERY -- NRO PASS 8812",
        "UNKNOWN (LARGE FACILITY)",
        "CONSTRUCTION OF HARDENED COMMAND BUNKER",
        "LIKELY ALTERNATE NATIONAL COMMAND AUTHORITY",
        "ZHUKOVSKY DISTRICT, MOSCOW OBLAST",
        "COORDINATES: 55.61N  038.12E",
        "SOVIET MINISTRY OF DEFENSE ENGINEERS",
        "CIVILIAN COVER -- CONSTRUCTION VEHICLES",
        "250000Z MAY 83  (FIRST OBSERVED)",
        "HEAVY EXCAVATION, BLAST-PROOF CONSTRUCTION",
        "ESTIMATED DEPTH: 100M -- EMP HARDENED"
    },
    {
        "SALUTE-030",
        "HUMINT / CONFIRMED BY TWO INDEPENDENT SOURCES",
        "UNKNOWN -- OFFICER CADRE ONLY (~30)",
        "EVACUATION OF FAMILIES FROM MOSCOW",
        "TO UNDISCLOSED RELOCATION SITES",
        "MOSCOW, VNUKOVO AIRPORT",
        "COORDINATES: 55.60N  037.26E",
        "SOVIET GENERAL STAFF -- CIVILIAN DRESS",
        "FAMILIES OF FLAG-RANK OFFICERS",
        "031400Z JUN 83",
        "CIVILIAN AIRCRAFT ONLY",
        "INDICATOR: LEADERSHIP EXPECTS CONFLICT IMMINENT"
    },

};

static const int SALUTE_POOL_SIZE = 30;
